### ISSUE TITLE
Provide detailed installation instructions

### ISSUE THREAD

**Issue by traversaro** [intelligent-soft-robots/o80#2]
It may be convenient for users to have easily accessible and usable installation instructions, ideally easily accessible from the repo README or the main documentation page (the current installation docs takes 4 clicks to reach from the README, assuming that you know where it is). 

There is currently the documentation in https://intelligent-soft-robots.github.io/code_documentation/o80/docs/html/doc/02.installation.html , but it is incomplete, in particular in the following points: 

> installing a few dependencies (apt and pip installation only)

The required apt and pip packages should be clearly listed, ideally by providing the exact commands that can be copy-pasted in the terminal to install them. I just now noticed that the dependencies are indeed listed in https://intelligent-soft-robots.github.io/code_documentation/o80_example/docs/html/doc/01_installation.html, but this is not easily reachable and in general at least the install documentation in a project should be self contained.

**Comment by vincentberenz** [comment]
@traversaro 

thanks for finding these issues

- the lists of dependencies has been added to https://intelligent-soft-robots.github.io/code_documentation/o80/docs/html/doc/02.installation.html
- the [readme](https://github.com/intelligent-soft-robots/o80) of o80 has now a direct link to the installation instruction page
- the broken links have been fixed

**Comment by traversaro** [comment]
Hi @vincentberenz , thanks for handling this. However, to be honest it is still not trivial to me how to install o80 and try some examples. In particular, I have no idea how (I actually have, but I tried to be a naive user for the sake of providing useful feedback) I am supposed to to the following steps: 
> creating a catkin workspace with o80 + dependencies packages (we use the project manager Treep to make this trivial)

Even if not completely self-contained, I would expect to have some pointers to the docs on how to install catkin on Ubuntu 18.04, and if necessary on how to install Treep. Furthermore, what are the `+ dependencies packages` ? If there is some more detailed documentation on some of the example packages, then I think it could make it sense to link it also from the o80 documentation.

**Comment by vincentberenz** [comment]
@traversaro looking back at this, I can see this is a valid concern. Here what I propose to do:

- the more detailed and practical installation procedure is provided in the o80_example. I believe this makes sense, as o80_example is the package that will result into concrete implementations of classes (and demos one can run). But the invitation to the user to look at the o80_example installation procedure is given late and is not emphasized. I can improve this.

- I can also improve the installation procedure of o80_example by providing better explanation regarding treep and catkin, as you suggest

- On top on this I can provide a docker image with o80_example already installed and ready to run

**Comment by traversaro** [comment]
Great @vincentberenz, I agree on all points.

**Comment by vincentberenz** [comment]
@traversaro I updated the docs

**Comment by vincentberenz** [comment]
@traversaro I added instructions on how to run the demos through docker containers

**Comment by traversaro** [comment]
Thanks @vincentberenz and sorry for the delay! The link in the previous comment is now broken.

**Comment by traversaro** [comment]
I am testing the new installation procedure documented in http://people.tuebingen.mpg.de/mpi-is-software/o80/docs/o80/doc/02.installation.html#from-binaries, and at least in the latest archive, it seems that the scripts are named `apt-dependencies` and `pip3-dependencies`, instead of `apt_dependencies` and `pip3_dependencies` as listed in the docs.

**Comment by vincentberenz** [comment]
@traversaro thanks for catching these typos. I fixed them
